# Generated by Django 6.0.3 on 2026-04-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('vitamins', models.CharField(max_length=200)),
                ('benefits', models.TextField()),
                ('disease_cure', models.TextField()),
                ('fertilizers', models.TextField()),
                ('expected_yield', models.CharField(max_length=100)),
            ],
        ),
    ]
